### ISSUE TITLE
Website Not Working?

### ISSUE THREAD

**Issue by Bved123** [hpcodecraft/splash-ds#2]
Every time i try to load the website i get the error: 

"404 
There isn't a GitHub Pages site here."

**Comment by Bved123** [comment]
Solution: Go to Actions ->pages build and deployment #1 -> deploy

But the "download splash screen" button seems to be broken

Edit: It started working

**Comment by jigglycrumb** [comment]
@Bved123 Did you come from Github or from an external site? Github links should be fixed now!
